### ISSUE TITLE
Interpolation indices wrong

### ISSUE THREAD

**Issue by AbsurdePhoton** [JakubOchnik/Cube-LUT-Loader#1]
Hi, according to https://en.wikipedia.org/wiki/Trilinear_interpolation#Method, you should check the indices you're using in the LUT table.

For example : 
    vector<float> vr_gz_bz = sum(mul(lut.LUT3D[R0][G0][B0], 1 - delta_r), mul(lut.LUT3D[R0][G0][B0], delta_r));
should be :
    vector<float> vr_gz_bz = sum(mul(lut.LUT3D[R0][G0][B0], 1 - delta_r), mul(lut.LUT3D[R1][G0][B0], delta_r));
etc.

I had banding issues with your code, but checking the vector indices resolved the problem.

Hope that helps.

**Comment by JakubOchnik** [comment]
Thank you, I solved the issue 😄
