### ISSUE TITLE
Request: Build Instructions

### ISSUE THREAD

**Issue by QueenOfSquiggles** [JakubOchnik/Cube-LUT-Loader#11]
I'm working on compiling this for myself to use for converting some LUTs into a format supported by Godot Game Engine. I think I'm figuring it out, but it would be really helpful if you included some build instructions. I'm on linux so I'm working on figuring out which libraries I need to install. Thanks for making this tool! It was exactly what I needed!

**Comment by JakubOchnik** [comment]
Done - added building instructions. Feel free to let me know if you have any other problems.

If your goal is to read LUTs and convert them to another format, you probably will be most interested in the parser code (`CubeLUT.cpp` file). If you separate it, you'd only need the Eigen library for that part (you can also remove the Tensors and achieve the same with multidimensional vectors/arrays).
