### ISSUE TITLE
Not working Lut

### ISSUE THREAD

**Issue by stephane-archer** [JakubOchnik/Cube-LUT-Loader#13]
Hi, thanks for making this project.
you can find attached below a few Luts I can't make work with your program.
Could you have a look? Is there any additional parameter I should specify?
[notWorkingLut.zip](https://github.com/JakubOchnik/Cube-LUT-Loader/files/12327547/notWorkingLut.zip)

**Comment by JakubOchnik** [comment]
The issue was related to handling LUT files with CRLF line endings. Now it should work properly.

**Comment by stephane-archer** [comment]
@JakubOchnik you are the best!

**Comment by JakubOchnik** [comment]
Sure, here's the specification: https://web.archive.org/web/20220220033515/https://wwwimages2.adobe.com/content/dam/acom/en/products/speedgrade/cc/pdfs/cube-lut-specification-1.0.pdf
