### ISSUE TITLE
Lut infinite parsing and eating CPU for breakfast

### ISSUE THREAD

**Issue by stephane-archer** [JakubOchnik/Cube-LUT-Loader#22]
[problematiclut.zip](https://github.com/JakubOchnik/Cube-LUT-Loader/files/12668176/problematiclut.zip)

I found this Lut that never finishes parsing and eats all my CPU, I would be glad if you could have a look at what is going on.

You are the best

**Comment by JakubOchnik** [comment]
It's caused by the lack of quotation marks after the "TITLE" keyword.
If you change that line to `TITLE	"ALog To ARRI Log C"`, it will work. I'll provide a fix soon.
