### ISSUE TITLE
Feature request: Modify CMake to add an option to build OpenCV statically like BUILD_CUDA

### ISSUE THREAD

**Issue by stephane-archer** [JakubOchnik/Cube-LUT-Loader#26]

**Comment by JakubOchnik** [comment]
Please take a look at the new Conan build - it should link OpenCV and Boost statically by default (unless the shared linking is enabled in `conanfile.txt`).

**Comment by stephane-archer** [comment]
@JakubOchnik thank you so much for taking the time to help me. I have a week of vacation which starts tomorrow so I will not be able to test your change but as soon as I go back home I will let you know if it works on my side :)
You are the best :)

**Comment by stephane-archer** [comment]
@JakubOchnik I was able to compile the project to the latest version easily, the transition to `conan` has been smooth and everything looks to work perfectly. Thanks again for your help and amazing work.
